version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cinephoria
      MYSQL_USER: cinephoria_user
      MYSQL_PASSWORD: cinepass
    ports:
      - "3306:3306"