name: CI/CD - Cinephoria

# Déclenchement à chaque push ou pull request sur la branche main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test APK
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code
    - uses: actions/checkout@v3

    # 2. Installer Java 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # 3. Construire l’APK
    - name: Build APK
      run: ./gradlew assembleDebug

    # 4. Lancer les tests unitaires
    - name: Run Tests
      run: ./gradlew test

  deploy:
    name: Deploy APK
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Publier l’APK dans les Releases GitHub
    - name: Upload APK to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/debug/app-debug.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
